### ISSUE TITLE
Dafuqq is going on

### ISSUE THREAD

**Issue by dafuqqs** [linescoin/lines#1]

**Comment by dafuqqs** [comment]
Also, that is one huge ass premine!

**Comment by linescoin** [comment]
New great coin has born!

**Comment by dafuqqs** [comment]
Bullshit! You've run two testnet already with no clear indication as to when you are actually going to release main .... if you didn't want some folks to jump in ahead of time you should've never put this on Github to begin with. Carry on this way and your trust is going to reach zero. Stop creating extra work. With that said, I hope you plan on releasing a windows wallet along with your linux build. If not, you might as well kill this project before it's even started. So, any idea when you release main?

**Comment by dafuqqs** [comment]
Ps. lol, and that with a 40 million pre-mine? You ain't flying anywhere with that :no_entry:
